export { AboutPageComponent } from './about-page/about-page.component';
export { CreatePageComponent } from './create-page/create-page.component';
export { DetailsPageComponent } from './details-page/details-page.component';
export { MainPageComponent } from './main-page/main-page.component';
export { NotFoundPageComponent } from './not-found-page/not-found-page.component';
export { ProfilePageComponent } from './profile-page/profile-page.component';
export { ResetPasswordPageComponent } from './reset-password-page/reset-password-page.component';
export { SigninPageComponent } from './signin-page/signin-page.component';
export { SignupPageComponent } from './signup-page/signup-page.component';
